version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: "cimg/node:16.7"

    working_directory: ~/shoppingify-master/client
    
    steps:
      - run: node --version
      - run: npm install


