version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  build:
    working_directory: ~/shoppingify-master/client
    docker:
      - image: "cimg/node:16.10"

    steps:
      - checkout:
          path: ~/shoppingify-master
      - node/install:
          install-yarn: true
          node-version: "12.16.0"
      - run: node --version

