version: 2.1
orbs:
  node: circleci/node@5.0.0
  heroku: circleci/heroku@0.0.10
jobs:
  test_react:
    docker:
      - image: "cimg/node:16.7"
    working_directory: ~/shoppingify-master/client
    steps:
      - checkout:
          path: ~/shoppingify-master
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies
      - run: npm install
      - run: npm install --prefix=$HOME/.local --global vercel
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package.json"}}
      - run: npm run test
  deploy_react:
    working_directory: ~/shoppingify-master/client
    docker:
      - image: "cimg/node:16.7"
    steps:
      - checkout:
          path: ~/shoppingify-master
      - run:
          name: deployment setup
          when: on_success
          command: DEPLOY_STG="curl -x GET https://api.vercel.com/v1/integrations/deploy/prj_6tRcSTLdT6kNWaypZFRt4SUrSbZj/sflEm0X0QG"
      - run: bash -c "$DEPLOY_STG"

  test_laravel:
    working_directory: ~/shoppingify-master/server
    environment:
      BASH_ENV: ~/.bashrc
      HEROKU_APP: "shoppingifyapi"
    docker:
      - image: circleci/php:8
        environment:
          APP_ENV: example
          DB_CONNECTION: mysql
          DB_DATABASE: server
          DB_USERNAME: root
          DB_PASSWORD: root
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: server

    steps:
      - checkout:
          path: ~/shoppingify-master/

      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libmcrypt-dev libsqlite3-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev zlib1g-dev
      - run:
          name: Install PHP Extensions
          command: |
            sudo docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install -j$(nproc) iconv gd zip pdo_mysql pdo_sqlite
            sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            sudo apt install -y mariadb-client

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run:
          name: Install Composer Dependencies
          command: composer install -n --ignore-platform-reqs

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: config mysql
          command: mysqladmin create test --host="127.0.0.1" --user="root" --password="root"
      - run:
          name: Populate .env
          command: cp .env.example .env && php artisan key:generate
      - run:
          name: Migrate Database
          command: |
            php artisan config:clear
            php artisan migrate --env=example --force
      - run: ./vendor/bin/phpunit




workflows:
  version: 2
  build_and_test:
    jobs:
      - test_laravel
      - test_react
      - heroku/deploy-via-git:
          requires:
            - test_laravel
            - test_react
      - deploy_react:
          requires:
            - test_laravel
            - test_react
            - heroku/deploy-via-git
