version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  install-node:
    docker:
      - image: "cimg/node:16.10"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run: node --version

workflows:
  
  run-npm-command:
    jobs:
      - node/run:
          working_directory: ~/client
          npm-run: build
          app-dir: ~/client
