version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    working_directory: ~/shoppingify-master/client
    docker:
      - image: "cimg/node:16.7"

    steps:
      - checkout:
          path: ~/shoppingify-master
      - node/install:
          install-yarn: true
          node-version: "16.7.0"
      - run: node --version

