version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  install-node:
    docker:
      - image: "cimg/node:16.10"

workflows:
  working_directory: /client
  run-npm-command:
    jobs:
      - node/run:
        npm-run: build
