version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: "cimg/node:16.7"

    working_directory: ~/shoppingify-master/client

    steps:
      - checkout:
          path: ~/shoppingify-master
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies
      - run: npm install
      - run: npm install --prefix=$HOME/.local --global vercel
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package.json"}}
      - run: npm run test
      - run: DEPLOY_STG="curl -x GET https://api.vercel.com/v1/integrations/deploy/prj_6tRcSTLdT6kNWaypZFRt4SUrSbZj/sflEm0X0QG"
      - run:
          name: deploy
          when: on_success
          command: bash -c "$DEPLOY_STG"
        

