version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  install-node:
    working_directory: ~/shoppingify-master/client
    docker:
      - image: "cimg/node:16.10"
    
    steps:
      - checkout:
          path: ~/shoppingify-master
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run: node --version

